export const TEMP_TICKET_TEST_PROFILES = [
  {
    id: 'thermal-58-readable',
    label: '58mm legible',
    paperLabel: '58mm',
    description: 'Compacto, con nombres partidos en lineas.',
    widthMm: 58,
    lineWidth: 34,
    fontSize: 9.5,
    lineHeight: 1.08,
    horizontalPadding: 0,
    wrapProductNames: true,
    productLineWidth: 22,
  },
  {
    id: 'thermal-72-wide',
    label: '72mm medio',
    paperLabel: '72mm',
    description: 'Mas aire para importes y nombres medianos.',
    widthMm: 72,
    lineWidth: 42,
    fontSize: 10.25,
    lineHeight: 1.1,
    horizontalPadding: 0,
    wrapProductNames: true,
    productLineWidth: 26,
  },
  {
    id: 'thermal-80-full',
    label: '80mm ancho',
    paperLabel: '80mm',
    description: 'El mas claro para productos largos.',
    widthMm: 80,
    lineWidth: 48,
    fontSize: 10.5,
    lineHeight: 1.12,
    horizontalPadding: 0,
    wrapProductNames: true,
    productLineWidth: 30,
  },
];
