export const CLOUD_SELECTS = {
  products: [
    'id',
    'title',
    'brand',
    'price',
    'purchasePrice',
    'stock',
    'category',
    'barcode',
    'image',
    'image_thumb',
    'supplier_links',
    'product_type',
    'expiration_date',
    'is_active',
    'created_at',
    'updated_at',
  ].join(','),
  productsList: [
    'id',
    'title',
    'brand',
    'price',
    'purchasePrice',
    'stock',
    'category',
    'barcode',
    'image',
    'image_thumb',
    'supplier_links',
    'product_type',
    'expiration_date',
    'is_active',
    'created_at',
    'updated_at',
  ].join(','),
  clients: [
    'id',
    'name',
    'member_number',
    'dni',
    'phone',
    'email',
    'extraInfo',
    'social_connections',
    'points',
    'is_active',
    'created_at',
  ].join(','),
  agendaContacts: [
    'id',
    'name',
    'phone',
    'email',
    'notes',
    'address',
    'contact_type',
    'tax_id',
    'contact_person',
    'is_active',
    'created_at',
    'updated_at',
  ].join(','),
  categories: 'name',
  rewards: [
    'id',
    'title',
    'description',
    'points_cost',
    'type',
    'discount_amount',
    'stock',
    'is_active',
  ].join(','),
  registerState: [
    'id',
    'is_open',
    'opening_balance',
    'closing_time',
    'opened_at',
    'last_updated_by',
  ].join(','),
  offers: [
    'id',
    'name',
    'type',
    'apply_to',
    'products_included',
    'items_count',
    'discount_value',
    'offer_price',
    'profit_margin',
    'created_by',
    'is_active',
    'created_at',
  ].join(','),
  sales: [
    'id',
    'created_at',
    'total',
    'payment_method',
    'payment_breakdown',
    'installments',
    'cash_received',
    'cash_change',
    'client_id',
    'points_earned',
    'points_spent',
    'order_id',
    'points_source',
    'status',
    'voided_at',
    'user_id',
    'user_role',
    'user_name',
    'sale_items(product_id,product_title,quantity,price,subtotal,is_reward,cost,is_custom,is_discount,is_combo,product_type)',
    'clients(name,member_number)',
  ].join(','),
  salesHistorySummary: [
    'id',
    'created_at',
    'total',
    'payment_method',
    'payment_breakdown',
    'installments',
    'cash_received',
    'cash_change',
    'client_id',
    'points_earned',
    'points_spent',
    'order_id',
    'points_source',
    'status',
    'voided_at',
    'user_id',
    'user_role',
    'user_name',
    'sale_items(product_id,product_title,quantity,price,subtotal,is_reward,cost,is_custom,is_discount,is_combo,product_type)',
    'clients(name,member_number)',
  ].join(','),
  logs: [
    'id',
    'created_at',
    'action',
    'details',
    'reason',
    'user',
  ].join(','),
  logsSummary: [
    'id',
    'created_at',
    'action',
    'reason',
    'user',
  ].join(','),
  expenses: [
    'id',
    'created_at',
    'expense_date',
    'description',
    'amount',
    'category',
    'payment_method',
    'user_id',
    'user_role',
    'user_name',
  ].join(','),
  cashClosuresSummary: [
    'id',
    'created_at',
    'date',
    'open_time',
    'close_time',
    'user_name',
    'user_id',
    'user_role',
    'type',
    'opening_balance',
    'total_sales',
    'final_balance',
    'total_cost',
    'total_expenses',
    'net_profit',
    'sales_count',
    'average_ticket',
    'new_clients_list',
  ].join(','),
  cashClosuresDetail: [
    'id',
    'created_at',
    'date',
    'open_time',
    'close_time',
    'user_name',
    'user_id',
    'user_role',
    'type',
    'opening_balance',
    'total_sales',
    'final_balance',
    'total_cost',
    'total_expenses',
    'net_profit',
    'sales_count',
    'average_ticket',
    'payment_methods_summary',
    'items_sold_list',
    'new_clients_list',
    'expenses_snapshot',
    'transactions_snapshot',
  ].join(','),
  budgets: [
    'id',
    'member_id',
    'customer_name',
    'customer_phone',
    'customer_note',
    'document_title',
    'event_label',
    'payment_method',
    'payment_breakdown',
    'installments',
    'items_snapshot',
    'total_amount',
    'created_at',
    'is_active',
  ].join(','),
  orders: [
    'id',
    'budget_id',
    'member_id',
    'customer_name',
    'customer_phone',
    'customer_note',
    'document_title',
    'event_label',
    'payment_method',
    'payment_breakdown',
    'installments',
    'items_snapshot',
    'total_amount',
    'deposit_amount',
    'paid_total',
    'points_credited',
    'points_accounting_mode',
    'version',
    'remaining_amount',
    'pickup_date',
    'status',
    'created_at',
    'is_active',
  ].join(','),
  memberPointEntries: [
    'id',
    'client_id',
    'order_id',
    'sale_id',
    'operation_key',
    'entry_type',
    'delta',
    'balance_after',
    'earned_at',
    'reason',
    'actor_id',
    'actor_name',
    'metadata',
    'created_at',
  ].join(','),
  appUsersPublicLogin: [
    'id',
    'display_name',
    'role',
    'avatar',
    'name_color',
    'theme',
    'metrics_view_mode',
    'is_active',
  ].join(','),
  appUsersPublicFull: [
    'id',
    'display_name',
    'role',
    'avatar',
    'name_color',
    'theme',
    'metrics_view_mode',
    'is_active',
  ].join(','),
};

export const DASHBOARD_LOG_LIMIT = 100;
export const LOGS_PAGE_SIZE = 50;
export const REPORTS_PAGE_SIZE = 50;
export const SESSIONS_PAGE_SIZE = 50;

export const HISTORY_LOG_ACTIONS = [
  'Nueva Venta',
  'Venta Realizada',
  'Venta Anulada',
  'Venta Restaurada',
  'Venta Eliminada',
  'Borrado Permanente',
  'Modificacion Pedido',
  'Modificación Pedido',
  'Venta Modificada',
];

export const isHistoryLogAction = (action) => HISTORY_LOG_ACTIONS.includes(action);

/**
 * Los logs del Historial partidos en dos, por peso.
 *
 * Medido en prod el 1-sep-2026:
 *   - eventos (anular / restaurar / eliminar / modificar):  221 filas / 220 kB
 *   - snapshots ("Venta Realizada"):                      3.964 filas / 5,8 MB
 *
 * Los snapshots son casi todos redundantes: la fila de `sales` ya trae sus
 * `sale_items` y el vendedor. Solo hacen falta para 16 ventas viejas que
 * quedaron sin items y para las 15 que ya no tienen fila. Por eso el feed baja
 * los eventos enteros y los snapshots uno por uno, cuando hacen falta.
 */
export const HISTORY_EVENT_LOG_ACTIONS = [
  'Venta Anulada',
  'Venta Restaurada',
  'Venta Eliminada',
  'Borrado Permanente',
  'Venta Modificada',
  'Modificacion Pedido',
  'Modificación Pedido',
];

export const HISTORY_SNAPSHOT_LOG_ACTIONS = ['Venta Realizada', 'Nueva Venta'];

export const SESSION_LOG_ACTIONS = [
  'Sesion Iniciada',
  'Sesion Cerrada',
  'Sesion Ausente',
  'Sesion Reanudada',
  'Sesion Expirada',
  'Sesión Iniciada',
  'Sesión Cerrada',
  'Sesión Ausente',
  'Sesión Reanudada',
  'Sesión Expirada',
  'Inicio de Sesión',
  'Cierre de Sesión',
  'Ausencia de Sesión',
  'Reanudación de Sesión',
  'Expiración de Sesión',
];
