export const CLOUD_SELECTS = {
  products: [
    'id',
    'title',
    'brand',
    'price',
    'purchasePrice',
    'stock',
    'category',
    'barcode',
    'image',
    'image_thumb',
    'product_type',
    'expiration_date',
    'is_active',
    'created_at',
  ].join(','),
  clients: [
    'id',
    'name',
    'member_number',
    'dni',
    'phone',
    'email',
    'points',
    'is_active',
    'created_at',
  ].join(','),
  agendaContacts: [
    'id',
    'name',
    'phone',
    'email',
    'notes',
    'address',
    'contact_type',
    'tax_id',
    'contact_person',
    'is_active',
    'created_at',
    'updated_at',
  ].join(','),
  categories: 'name',
  rewards: [
    'id',
    'title',
    'description',
    'points_cost',
    'type',
    'discount_amount',
    'stock',
  ].join(','),
  registerState: [
    'id',
    'is_open',
    'opening_balance',
    'closing_time',
    'opened_at',
    'last_updated_by',
  ].join(','),
  offers: [
    'id',
    'name',
    'type',
    'apply_to',
    'products_included',
    'items_count',
    'discount_value',
    'offer_price',
    'profit_margin',
    'created_by',
    'is_active',
    'created_at',
  ].join(','),
  sales: [
    'id',
    'created_at',
    'total',
    'payment_method',
    'payment_breakdown',
    'cash_received',
    'cash_change',
    'installments',
    'client_id',
    'points_earned',
    'points_spent',
    'status',
    'sale_items(product_id,product_title,quantity,price,is_reward)',
    'clients(name,member_number)',
  ].join(','),
  salesHistorySummary: [
    'id',
    'created_at',
    'total',
    'payment_method',
    'payment_breakdown',
    'cash_received',
    'cash_change',
    'installments',
    'client_id',
    'points_earned',
    'points_spent',
    'status',
    'sale_items(product_id,product_title,quantity,price,is_reward)',
    'clients(name,member_number)',
  ].join(','),
  logs: [
    'id',
    'created_at',
    'action',
    'details',
    'reason',
    'user',
  ].join(','),
  logsSummary: [
    'id',
    'created_at',
    'action',
    'reason',
    'user',
  ].join(','),
  expenses: [
    'id',
    'created_at',
    'description',
    'amount',
    'category',
    'payment_method',
  ].join(','),
  cashClosuresSummary: [
    'id',
    'created_at',
    'date',
    'open_time',
    'close_time',
    'user_name',
    'type',
    'opening_balance',
    'total_sales',
    'final_balance',
    'total_cost',
    'total_expenses',
    'net_profit',
    'sales_count',
    'average_ticket',
    'new_clients_list',
  ].join(','),
  cashClosuresDetail: [
    'id',
    'created_at',
    'date',
    'open_time',
    'close_time',
    'user_name',
    'type',
    'opening_balance',
    'total_sales',
    'final_balance',
    'total_cost',
    'total_expenses',
    'net_profit',
    'sales_count',
    'average_ticket',
    'payment_methods_summary',
    'items_sold_list',
    'new_clients_list',
    'expenses_snapshot',
    'transactions_snapshot',
  ].join(','),
  budgets: [
    'id',
    'member_id',
    'customer_name',
    'customer_phone',
    'customer_note',
    'document_title',
    'event_label',
    'payment_method',
    'payment_breakdown',
    'installments',
    'items_snapshot',
    'total_amount',
    'created_at',
    'is_active',
  ].join(','),
  orders: [
    'id',
    'budget_id',
    'member_id',
    'customer_name',
    'customer_phone',
    'customer_note',
    'document_title',
    'event_label',
    'payment_method',
    'payment_breakdown',
    'installments',
    'items_snapshot',
    'total_amount',
    'deposit_amount',
    'paid_total',
    'remaining_amount',
    'pickup_date',
    'status',
    'created_at',
    'is_active',
  ].join(','),
  appUsersPublicLogin: [
    'id',
    'display_name',
    'role',
    'avatar',
    'name_color',
    'theme',
    'is_active',
    'permissions_override',
    'permissions_version',
    'force_reauth_permissions_version',
  ].join(','),
  appUsersPublicFull: [
    'id',
    'display_name',
    'role',
    'avatar',
    'name_color',
    'theme',
    'is_active',
    'permissions_override',
    'permissions_version',
    'force_reauth_permissions_version',
    'created_at',
    'updated_at',
    'created_by',
    'source',
  ].join(','),
};

export const DASHBOARD_LOG_LIMIT = 100;
export const LOGS_PAGE_SIZE = 50;
export const REPORTS_PAGE_SIZE = 50;
export const SESSIONS_PAGE_SIZE = 50;

export const HISTORY_LOG_ACTIONS = [
  'Nueva Venta',
  'Venta Realizada',
  'Venta Anulada',
  'Venta Restaurada',
  'Venta Eliminada',
  'Borrado Permanente',
  'Modificacion Pedido',
  'Modificación Pedido',
  'Venta Modificada',
];

export const SESSION_LOG_ACTIONS = [
  'Sesion Iniciada',
  'Sesion Cerrada',
  'Sesion Ausente',
  'Sesion Reanudada',
  'Sesion Expirada',
  'Sesión Iniciada',
  'Sesión Cerrada',
  'Sesión Ausente',
  'Sesión Reanudada',
  'Sesión Expirada',
  'Inicio de Sesión',
  'Cierre de Sesión',
  'Ausencia de Sesión',
  'Reanudación de Sesión',
  'Expiración de Sesión',
];
